services:
  deep_learning_api:
    image: toublouprosper/infotrustai-deeplearning:latest
    ports:
      - "127.0.0.1:8088:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    networks:
      - infotrustai_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  core_api:
    image: toublouprosper/infotrustai-core:latest
    ports:
      - "8089:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - AI_AGENT_API_URL=${AI_AGENT_API_URL}
      - DEEP_LEARNING_API_URL=http://deep_learning_api:5000/predict
    restart: unless-stopped
    depends_on:
      deep_learning_api:
        condition: service_started
    networks:
      - infotrustai_net

  frontend:
    image: toublouprosper/infotrustai-frontend
    ports:
      - "8000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - API_URL=${CORE_API_URL}
    restart: unless-stopped
    depends_on:
      - core_api
    networks:
      - infotrustai_net

networks:
  infotrustai_net:
    driver: bridge
